#!/bin/ksh

# @ shell = /usr/bin/ksh
# @ class = cluster
# @ startdate = 07/02/2009 20:30
# @ job_type = parallel
# @ job_name = lesrico
# @ output   = $(job_name).$(jobid).out
# @ error    = $(job_name).$(jobid).err
# @ notification = start
# @ notify_user = louise.nuijens@zmaw.de
# @ wall_clock_limit = 08:00:00
# @ node_usage = not_shared
# @ network.MPI = sn_all,not_shared,us
# @ tasks_per_node = 64
# @ node = 2
# @ resources = ConsumableMemory(0.75gb)
# @ task_affinity = cpu(1)
# @ queue

timex poe ./les.mpi
