#!/bin/bash
#-----------------------------------------------------------------------------
# SGE directives
#
#$ -S /bin/bash
#$ -o $JOB_NAME.o$JOB_ID
#$ -cwd
#$ -q cluster
#$ -j n
#$ -N JOB_NAME
#$ -M malte.rieck@zmaw.de
#$ -pe orte8 64
#-----------------------------------------------------------------------------
# user command section

export MPIROOT=/sw/sles10-x64/ofed/openmpi-1.4.0-intel11
export PATH=$MPIROOT/bin:$PATH

echo -n " Job started at: "
date
echo -n " Executed by host: "
hostname
#-----------------------------------------------------------------------------
mpiexec -np 64 ./les.mpi
#-----------------------------------------------------------------------------
echo -n " Job completed at: "
date
#-----------------------------------------------------------------------------
