set (ENV{NETCDF_ROOT} /sw/squeeze-x64/netcdf-latest-static-gcc45)
set (ENV{HDF5_ROOT} /home/zmaw/m300241/models/hdf5-1.8.9)
set (ENV{FFTW_ROOT} /sw/squeeze-x64/fftw-3.2.1)
set (NETCDF_USE_STATIC_LIBRARIES TRUE)
set (HDF5_USE_STATIC_LIBRARIES FALSE)
