set (ENV{NETCDF_ROOT} /sw/sles10-x64/netcdf-latest-static-gcc45)
set (ENV{HDF5_ROOT} /sw/sles10-x64/hdf5-1.8.7-static)
set (ENV{FFTW_ROOT} /sw/sles10-x64/fftw-3.2.1)
set (CMAKE_LIBRARY_PATH /usr/lib64)
set (NETCDF_USE_STATIC_LIBRARIES TRUE)
set (HDF5_USE_STATIC_LIBRARIES TRUE)
